# Generated by Django 4.0.3 on 2022-03-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_food_plan_bot', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в телеграмме')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Предпочтение')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название блюда')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeClassificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.preferences')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество ингредиента')),
                ('ingredient_measure', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('paid_until', models.DateField()),
                ('person_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество персон')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.customers', verbose_name='Подписка')),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_food_plan_bot.preferences', verbose_name='Предпочтение')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='tg_food_plan_bot.RecipeIngredients', to='tg_food_plan_bot.ingredients'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preferences',
            field=models.ManyToManyField(through='tg_food_plan_bot.RecipeClassificator', to='tg_food_plan_bot.preferences'),
        ),
    ]
